export const ActionTypes = {
    // theme
    CHANGE_THEME: "CHANGE_THEME",

    // login
    USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
    UPDATE_LOGIN_STATE: "UPDATE_LOGIN_STATE",

    // register
    USER_SIGNUP_REQUEST: "USER_SIGNUP_REQUEST",
    USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
    USER_SIGNUP_FAILURE: "USER_SIGNUP_FAILURE",
    UPDATE_SIGNUP_STATE: "UPDATE_SIGNUP_STATE",

    // sign out
    USER_SIGNOUT: "USER_SIGNOUT",

    // notification
    SHOW_NOTIFICATION: "SHOW_NOTIFICATION",
    HIDE_NOTIFICATION: "HIDE_NOTIFICATION",

    // search
    SEARCH_REQUEST: "SEARCH_REQUEST",
    SEARCH_SUCCESS: "SEARCH_SUCCESS",
    SEARCH_FAILURE: "SEARCH_FAILURE",
    UPDATE_SEARCH_STATE: "UPDATE_SEARCH_STATE",
};
