export const dummyFriends = [
    {
        title: 'Friends',
        content: [
            {
                name: 'Sandeep Kumar',
                username: 'sandeep',
                email: '',
                id: '17',
            },
            {
                name: 'Aravind Karnam',
                username: 'aravind',
                email: '',
                id: '21',
            },
            {
                name: 'Abhishek Saklani',
                username: 'saklani',
                email: '',
                id: '12',
            },
            {
                name: 'Prakhar Narayan',
                username: 'prakhar',
                email: '',
                id: '35',
            },
            {
                name: 'Abhishek Ray',
                username: 'ray',
                email: '',
                id: '33',
            },
            {
                name: 'Akshay Kadam',
                username: 'akshay',
                email: '',
                id: '65',
            },
            {
                name: 'Anirban Majumdar',
                username: 'anirban',
                email: '',
                id: '47',
            },
            {
                name: 'Azaan Ahmed',
                username: 'azaan',
                email: '',
                id: '22',
            },
            {
                name: 'Gaurav Parmar',
                username: 'gaurav',
                email: '',
                id: '34',
            },
            {
                name: 'Mayank Mishra',
                username: 'mayank',
                email: '',
                id: '55',
            },
        ]
    }
];

export const dummyChat = {
    user: {
        name: 'Sandeep Kumar',
        username: 'sandeep',
        email: '',
        id: '17',
    },
    messages: [
        {
            name: 'Sai Kiran',
            username: 'sai',
            id: '19',
            message: 'Hi, I\'m Sai Kiran',
        },
        {
            name: 'Sandeep Kumar',
            username: 'sandeep',
            id: '17',
            message: 'Hi Sai, I\'m Sandeep!',
        },
        {
            name: 'Sai Kiran',
            username: 'sai',
            id: '19',
            message: 'Hi Sandeep, how are you doing?',
        },
        {
            name: 'Sandeep Kumar',
            username: 'sandeep',
            id: '17',
            message: 'I\'m fine, how about you?',
        },
        {
            name: 'Sai Kiran',
            username: 'sai',
            id: '19',
            message: 'I\'m doing fine. Did you listen to the latest Charlie Puth\'s song?',
        },
        {
            name: 'Sandeep Kumar',
            username: 'sandeep',
            id: '17',
            message: 'Yeah, I\'ve just heard it. It\'s so good! This is now one of my favourites.',
        },
    ],
};

export const dummyPlaylists = {
    title: 'Playlists',
    default: [
        {
            id: 'home',
            name: 'Home',
            value: 'home',
            type: 'dashboard',
        },
        {
            id: 'discover',
            name: 'Discover',
            value: 'discover',
            type: 'new',
        },
        {
            id: 'liked',
            name: 'Liked Songs',
            value: 'liked',
            type: 'playlist',
        },
    ],
    content: [
        {
            id: 24,
            name: 'Today\'s Top Hits',
            value: 'topHits',
            type: 'playlist',
        },
        {
            id: 101,
            name: 'Power Workout',
            value: 'workout',
            type: 'playlist',
        },
        {
            id: 97,
            name: 'Desi Party',
            value: 'desi',
            type: 'playlist',
        },
        {
            id: 158,
            name: 'Deep Focus',
            value: 'focus',
            type: 'playlist',
        },
        {
            id: 234,
            name: 'This is Arijit Singh',
            value: 'arijit',
            type: 'playlist',
        },
        {
            id: 141,
            name: 'New Releases',
            value: 'releases',
            type: 'playlist',
        },
        {
            id: 34,
            name: 'Sad Vibes',
            value: 'sad',
            type: 'playlist',
        },
        {
            id: 133,
            name: 'Lofi Beats',
            value: 'lofi',
            type: 'playlist',
        },
        {
            id: 149,
            name: 'Tollywood Mix',
            value: 'tolly',
            type: 'playlist',
        },
        {
            id: 216,
            name: 'Soft Instrumental',
            value: 'instrumental',
            type: 'playlist',
        },
        {
            id: 82,
            name: 'Hip Hop Central',
            value: 'hiphop',
            type: 'playlist',
        },
        {
            id: 31,
            name: 'Electronic Dance',
            value: 'electronic',
            type: 'playlist',
        },
    ],
};

export const dummyPlaylist = {
    id: 24,
    name: 'Today\'s Top Hits',
    value: 'topHits',
    songs: [
        {
            id: 44,
            name: 'As It Was',
            artist: 'Harry Styles',
            duration: '2:47',
            durationInSec: 167,
            album: 'As It Was',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: true,
        },
        {
            id: 94,
            name: 'Light Switch',
            artist: 'Charlie Puth',
            duration: '3:07',
            durationInSec: 187,
            album: 'CHARLIE',
            art: '/stock/charlie-album.png',
            release: 2022,
            playlistId: 24,
            liked: false,
        },
        {
            id: 47,
            name: 'I\'m Good',
            artist: 'David Guetta, Bebe Rexa',
            duration: '2:55',
            durationInSec: 175,
            album: 'I\'m Good',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: false,
        },
        {
            id: 18,
            name: 'Headlights',
            artist: 'Alan Walker',
            duration: '2:38',
            durationInSec: 158,
            album: 'Headlights',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: true,
        },
        {
            id: 67,
            name: 'Under The Influence',
            artist: 'Chris Brown',
            duration: '3:04',
            durationInSec: 184,
            album: 'Under The Influence',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: false,
        },
        {
            id: 36,
            name: 'The Fall',
            artist: 'The Chainsmokers, Ship Wrek',
            duration: '3:16',
            durationInSec: 196,
            album: 'So Far So Good',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: false,
        },
        {
            id: 88,
            name: 'Cooped Up',
            artist: 'Post Malone, Roddy Richh',
            duration: '3:06',
            durationInSec: 186,
            album: 'Twelve Carat Toothache',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: true,
        },
        {
            id: 79,
            name: 'So Good',
            artist: 'Halsey',
            duration: '2:56',
            durationInSec: 176,
            album: 'So Good',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: false,
        },
        {
            id: 19,
            name: 'Honest',
            artist: 'Justin Bieber, Don Toliver',
            duration: '3:13',
            durationInSec: 193,
            album: 'Honest',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: true,
        },
        {
            id: 27,
            name: 'Woman',
            artist: 'Doja Cat',
            duration: '2:53',
            durationInSec: 173,
            album: 'Planet Her',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: false,
        },
    ],
}
