export const dummyFriends = [
    {
        title: 'Friends',
        content: [
            {
                name: 'Prashobh',
                username: 'prashobh',
                email: '',
                id: '17',
                isFriend: true,
                time: '4:34 PM',
                unreads: 2,
            },
            {
                name: 'Aniket Kumar Giri',
                username: 'aniket',
                email: '',
                id: '21',
                isFriend: false,
                time: '10:56 AM',
                unreads: 5,
            },
            {
                name: 'Aditya Panat',
                username: 'aditya',
                email: '',
                id: '12',
                isFriend: true,
                time: '9:17 AM',
                unreads: 0,
            },
            {
                name: 'Shreyansh',
                username: 'shreyansh',
                email: '',
                id: '35',
                isFriend: true,
                time: 'Yesterday, 6:25 PM',
                unreads: 0,
            },
            {
                name: 'Piyush Agrawal',
                username: 'piyush',
                email: '',
                id: '33',
                isFriend: false,
                time: '4/11/22',
                unreads: 0,
            },
            {
                name: 'Bhargav Gouriveni',
                username: 'bhargav',
                email: '',
                id: '65',
                isFriend: false,
                time: '4/11/22',
                unreads: 0,
            },
            {
                name: 'Pavan Kumar Reddy',
                username: 'pavan',
                email: '',
                id: '47',
                isFriend: true,
            },
            {
                name: 'Harshan Noone',
                username: 'harshan',
                email: '',
                id: '22',
                isFriend: false,
            },
            {
                name: 'Prabhu PJ',
                username: 'prabhu',
                email: '',
                id: '34',
                isFriend: false,
            },
            {
                name: 'Katta Rakesh Reddy',
                username: 'rakesh',
                email: '',
                id: '55',
                isFriend: true,
            },
            {
                name: 'Shubhasri Tadepalli',
                username: 'shubhasri',
                email: '',
                id: '63',
                isFriend: false,
            },
            {
                name: 'Lalita Tanmai',
                username: 'lalita',
                email: '',
                id: '41',
                isFriend: true,
            },
            {
                name: 'Gunti Sandhya',
                username: 'sandhya',
                email: '',
                id: '19',
                isFriend: true,
            },
            {
                name: 'Aman Deep Singh',
                username: 'aman',
                email: '',
                id: '25',
                isFriend: false,
            },
            {
                name: 'Soumalya Roy',
                username: 'soumalya',
                email: '',
                id: '27',
                isFriend: false,
            },
        ]
    }
];

export const dummyGroups = [
    {
        title: 'Groups',
        content: [
            {
                id: '21',
                name: 'BeyHive',
                description: 'Fans of Beyonce',
                members: 17,
                joined: false,
                time: '9:40 PM',
                unreads: 17,
            },
            {
                id: '17',
                name: 'Swift Squad',
                description: 'Fans of Taylor Swift',
                members: 21,
                joined: false,
                time: '8:56 PM',
                unreads: 5,
            },
            {
                id: '12',
                name: 'Firebreathers',
                description: 'Fans of Imagine Dragons',
                members: 12,
                joined: true,
                time: '6:31 PM',
                unreads: 9,
            },
            {
                id: '35',
                name: 'KatyCats',
                description: 'Fans of Katy Perry',
                members: 35,
                joined: true,
                time: '3:24 PM',
                unreads: 0,
            },
            {
                id: '33',
                name: 'Harmonizers',
                description: 'Fans of Fifth Harmony',
                members: 33,
                joined: false,
                time: '11:18 AM',
                unreads: 0,
            },
            {
                id: '65',
                name: 'The Backstreet Boys',
                description: 'Fans of Backstreet Boys, obviously!',
                members: 65,
                joined: true,
                time: 'Yesterday, 11:55 PM',
                unreads: 0,
            },
            {
                id: '47',
                name: 'The Weeknders',
                description: 'Fans of THe Weeknd',
                members: 47,
                joined: false,
            },
            {
                id: '22',
                name: 'Beliebers',
                description: 'Fans of Justin Bieber',
                members: 72,
                joined: true,
            },
            {
                id: '34',
                name: 'BTS A.R.M.Y',
                description: 'Fans of BTS',
                members: 52,
                joined: false,
            },
            {
                id: '55',
                name: 'Coldplayers',
                description: 'Fans of Coldplay',
                members: 55,
                joined: false,
            },
            {
                id: '31',
                name: 'Moonwalkers',
                description: 'Fans of Michael Jackson',
                members: 94,
                joined: false,
            },
            {
                id: '92',
                name: 'Rihanna Navy',
                description: 'Fans of Rihanna',
                members: 83,
                joined: true,
            },
            {
                id: '87',
                name: 'Sheerios',
                description: 'Fans of Ed Sheeran',
                members: 29,
                joined: true,
            },
        ]
    }
];

export const dummyChat = {
    user: {
        name: 'Prashobh',
        username: 'prashobh',
        email: '',
        id: '17',
    },
    messages: [
        {
            name: 'Sandeep',
            username: 'sai',
            id: '19',
            message: 'Hi, I\'m Sandeep',
        },
        {
            name: 'Prashobh',
            username: 'prashobh',
            id: '17',
            message: 'Hi Sandeep, I\'m Prashobh!',
        },
        {
            name: 'Sandeep',
            username: 'sai',
            id: '19',
            message: 'Hi Prashobh, how are you doing?',
        },
        {
            name: 'Prashobh',
            username: 'prashobh',
            id: '17',
            message: 'I\'m fine, how about you?',
        },
        {
            name: 'Sandeep',
            username: 'sai',
            id: '19',
            message: 'I\'m doing fine. Did you listen to the latest Charlie Puth\'s song?',
        },
        {
            name: 'Prashobh',
            username: 'prashobh',
            id: '17',
            message: 'Yeah, I\'ve just heard it. It\'s so good! This is now one of my favourites.',
        },
        {
            name: 'Sandeep',
            username: 'sai',
            id: '19',
            message: 'I\'m also waiting for Taylor Swift\'s album to drop, it\'s going to be lit!',
        },
        {
            name: 'Prashobh',
            username: 'prashobh',
            id: '17',
            message: 'Oh yeah! It\'s going to be released on this coming Friday, right?',
        },
        {
            name: 'Sandeep',
            username: 'sai',
            id: '19',
            message: 'Yess!',
        },
    ],
};

export const dummyPlaylists = {
    title: 'Playlists',
    default: [
        // {
        //     id: 'home',
        //     name: 'Home',
        //     value: 'home',
        //     type: 'dashboard',
        // },
        // {
        //     id: 'discover',
        //     name: 'Discover',
        //     value: 'discover',
        //     type: 'new',
        // },
        {
            id: 'liked',
            name: 'Favourites',
            value: 'liked',
            type: 'playlist',
        },
    ],
    content: [
        {
            id: 24,
            name: 'Today\'s Top Hits',
            value: 'topHits',
            type: 'playlist',
            following: true,
        },
        {
            id: 101,
            name: 'Power Workout',
            value: 'workout',
            type: 'playlist',
            following: true,
        },
        {
            id: 97,
            name: 'Desi Party',
            value: 'desi',
            type: 'playlist',
            following: false,
        },
        {
            id: 158,
            name: 'Deep Focus',
            value: 'focus',
            type: 'playlist',
            following: false,
        },
        {
            id: 234,
            name: 'This is Arijit Singh',
            value: 'arijit',
            type: 'playlist',
            following: true,
        },
        {
            id: 141,
            name: 'New Releases',
            value: 'releases',
            type: 'playlist',
            following: false,
        },
        {
            id: 34,
            name: 'Sad Vibes',
            value: 'sad',
            type: 'playlist',
            following: false,
        },
        {
            id: 133,
            name: 'Lofi Beats',
            value: 'lofi',
            type: 'playlist',
            following: false,
        },
        {
            id: 149,
            name: 'Tollywood Mix',
            value: 'tolly',
            type: 'playlist',
            following: true,
        },
        {
            id: 216,
            name: 'Soft Instrumental',
            value: 'instrumental',
            type: 'playlist',
            following: true,
        },
        {
            id: 82,
            name: 'Hip Hop Central',
            value: 'hiphop',
            type: 'playlist',
            following: false,
        },
        {
            id: 31,
            name: 'Electronic Dance',
            value: 'electronic',
            type: 'playlist',
            following: false,
        },
    ],
};

export const dummyPlaylist = {
    id: 24,
    name: 'Today\'s Top Hits',
    value: 'topHits',
    songs: [
        {
            id: 44,
            name: 'As It Was',
            artist: 'Harry Styles',
            duration: '2:47',
            durationInSec: 167,
            album: 'As It Was',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: true,
        },
        {
            id: 94,
            name: 'Light Switch',
            artist: 'Charlie Puth',
            duration: '3:07',
            durationInSec: 187,
            album: 'CHARLIE',
            art: '/stock/charlie-album.png',
            release: 2022,
            playlistId: 24,
            liked: true,
        },
        {
            id: 47,
            name: 'I\'m Good',
            artist: 'David Guetta, Bebe Rexa',
            duration: '2:55',
            durationInSec: 175,
            album: 'I\'m Good',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: true,
        },
        {
            id: 18,
            name: 'Headlights',
            artist: 'Alan Walker',
            duration: '2:38',
            durationInSec: 158,
            album: 'Headlights',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: true,
        },
        {
            id: 67,
            name: 'Under The Influence',
            artist: 'Chris Brown',
            duration: '3:04',
            durationInSec: 184,
            album: 'Under The Influence',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: false,
        },
        {
            id: 36,
            name: 'The Fall',
            artist: 'The Chainsmokers, Ship Wrek',
            duration: '3:16',
            durationInSec: 196,
            album: 'So Far So Good',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: false,
        },
        {
            id: 88,
            name: 'Cooped Up',
            artist: 'Post Malone, Roddy Richh',
            duration: '3:06',
            durationInSec: 186,
            album: 'Twelve Carat Toothache',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: true,
        },
        {
            id: 79,
            name: 'So Good',
            artist: 'Halsey',
            duration: '2:56',
            durationInSec: 176,
            album: 'So Good',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: false,
        },
        {
            id: 19,
            name: 'Honest',
            artist: 'Justin Bieber, Don Toliver',
            duration: '3:13',
            durationInSec: 193,
            album: 'Honest',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: true,
        },
        {
            id: 27,
            name: 'Woman',
            artist: 'Doja Cat',
            duration: '2:53',
            durationInSec: 173,
            album: 'Planet Her',
            art: '',
            release: 2022,
            playlistId: 24,
            liked: false,
        },
    ],
}

export const dummyArtists = [
    {
        id: 26,
        name: "Charlie Puth",
        following: true,
    },
    {
        id: 12,
        name: "Ed Sheeran",
        following: false,
    },
    {
        id: 33,
        name: "David Guetta",
        following: false,
    },
    {
        id: 98,
        name: "Taylor Swift",
        following: true,
    },
    {
        id: 43,
        name: "Alan Walker",
        following: true,
    },
    {
        id: 85,
        name: "Chris Brown",
        following: false,
    },
    {
        id: 76,
        name: "The Chainsmokers",
        following: true,
    },
    {
        id: 93,
        name: "Post Malone",
        following: true,
    },
    {
        id: 14,
        name: "Halsey",
        following: false,
    },
    {
        id: 49,
        name: "Justin Bieber",
        following: true,
    },
    {
        id: 27,
        name: "Doja Cat",
        following: false,
    },
    {
        id: 37,
        name: "Bebe Rexa",
        following: true,
    },
    {
        id: 41,
        name: "The Weeknd",
        following: false,
    },
    {
        id: 71,
        name: "Imagine Dragons",
        following: true,
    },
    {
        id: 59,
        name: "Dua Lipa",
        following: true,
    },
]

export const dummySearchResults = {
    profiles: dummyFriends[0].content,
    groups: dummyGroups[0].content,
    songs: dummyPlaylist.songs,
    playlists: dummyPlaylists.content,
    artists: dummyArtists,
}
